version: '3'

services:
  database:
    build:
      context: ./docker/database
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-symfony}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-symfony}
      MARIADB_USER: ${MARIADB_USER:-symfony}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-symfony}
    volumes:
      - ./docker/database/data:/var/lib/mysql:rw
    ports:
      - 3006:3306
    user: symfony
