name: Run Panther tests

on: [ push, pull_request ]

jobs:
  tests:

    runs-on: ubuntu-latest

    container: ubuntu
    services:
      database:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: symfony
          POSTGRES_PASSWORD: symfony
          POSTGRES_USER: symfony
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          extensions: apcu,json,xdebug,xsl
          ini-values: date.timezone=Europe/Paris,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,apc.enable_cli=1,zend.assertions=1
          php-version: '8.0'
          tools: pecl

      - name: Display versions
        run: |
          php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
          php -i

      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Javascript dependencies
        run: yarn

      - name: Build Javascript assets
        run: yarn build

      - name: Run test suite
        run: bin/phpunit
        env:
          POSTGRES_HOST: localhost