name: Run Panther tests

on: [ push, pull_request ]

jobs:
  tests:

    runs-on: ubuntu-latest

    container: ubuntu
    services:
      database:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: symfony
          POSTGRES_PASSWORD: symfony
          POSTGRES_USER: symfony
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Javascript dependencies
        run: yarn

      - name: Build Javascript assets
        run: yarn build

      - name: Run test suite
        run: bin/phpunit